/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIngestRouteImport } from './routes/admin.ingest'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as MoviesIndexRouteImport } from './routes/movies.index'
import { Route as MoviesSlugRouteImport } from './routes/movies.$slug'
import { Route as PodcastsIndexRouteImport } from './routes/podcasts.index'
import { Route as PodcastsSlugRouteImport } from './routes/podcasts.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngestRoute = AdminIngestRouteImport.update({
  id: '/admin/ingest',
  path: '/admin/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesSlugRoute = MoviesSlugRouteImport.update({
  id: '/movies/$slug',
  path: '/movies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsIndexRoute = PodcastsIndexRouteImport.update({
  id: '/podcasts/',
  path: '/podcasts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsSlugRoute = PodcastsSlugRouteImport.update({
  id: '/podcasts/$slug',
  path: '/podcasts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/lists/': typeof ListsIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/podcasts/': typeof PodcastsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/lists': typeof ListsIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/podcasts': typeof PodcastsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/lists/': typeof ListsIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/podcasts/': typeof PodcastsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/admin/ingest'
    | '/movies/$slug'
    | '/podcasts/$slug'
    | '/lists/'
    | '/movies/'
    | '/podcasts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/admin/ingest'
    | '/movies/$slug'
    | '/podcasts/$slug'
    | '/lists'
    | '/movies'
    | '/podcasts'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/admin/ingest'
    | '/movies/$slug'
    | '/podcasts/$slug'
    | '/lists/'
    | '/movies/'
    | '/podcasts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AdminIngestRoute: typeof AdminIngestRoute
  MoviesSlugRoute: typeof MoviesSlugRoute
  PodcastsSlugRoute: typeof PodcastsSlugRoute
  ListsIndexRoute: typeof ListsIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  PodcastsIndexRoute: typeof PodcastsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ingest': {
      id: '/admin/ingest'
      path: '/admin/ingest'
      fullPath: '/admin/ingest'
      preLoaderRoute: typeof AdminIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$slug': {
      id: '/movies/$slug'
      path: '/movies/$slug'
      fullPath: '/movies/$slug'
      preLoaderRoute: typeof MoviesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/': {
      id: '/podcasts/'
      path: '/podcasts'
      fullPath: '/podcasts/'
      preLoaderRoute: typeof PodcastsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$slug': {
      id: '/podcasts/$slug'
      path: '/podcasts/$slug'
      fullPath: '/podcasts/$slug'
      preLoaderRoute: typeof PodcastsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AdminIngestRoute: AdminIngestRoute,
  MoviesSlugRoute: MoviesSlugRoute,
  PodcastsSlugRoute: PodcastsSlugRoute,
  ListsIndexRoute: ListsIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  PodcastsIndexRoute: PodcastsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
